name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v2
      # Устанавливаем Node.JS для сборки приложения
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      # Устанавливаем зависимости для сборки
      - name: Install vsce
        run: npm install -g vsce
      - name: Install Dependencies
        run: npm i
      # Собираем приложение
      - name: Build
        run: vsce package